server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://db:5432/prodsyncdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret: "c1a2b3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2"
    expiration-ms: 86400000

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY:}